on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
    - master
    paths:
    - '.scripts/punit'
    - 'punit/**'
    - 'pyproject.toml'
    - 'README.md'
    - 'docs/**'
    - '.gitea/workflows/pipeline.yaml'
jobs:
  publish:
    name: "publish"
    runs-on: builder-py313
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: "Configure"
      run: |
        export SEMVER=$(conventional-semver)
        echo "REGISTRY_NAMESPACE=wilson0x4d" >> "$GITHUB_ENV"
        echo "SEMVER=$SEMVER" >> "$GITHUB_ENV"
        echo "PYPI_REPO=${{ vars.PYPI_REPO }}" >> "$GITHUB_ENV"
        curl -X POST "${{ gitea.api_url }}/repos/${{ gitea.repository }}/statuses/${{ gitea.sha }}" \
            -H "Authorization: token ${{ secrets.GITEA_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d "{
                  \"state\": \"pending\",
                  \"context\": \"SEMVER\",
                  \"description\": \"$SEMVER\"
                }"
    - name: "Execute"
      run: |
        cd '${{ gitea.workspace }}'
        sys/init-venv.sh
        sys/run-tests.sh
        sys/publish-packages.sh
