#!/bin/bash
# SPDX-FileCopyrightText: © 2024 Shaun Wilson
# SPDX-License-Identifier: MIT
##
set -eo pipefail
if [ -z "$VIRTUAL_ENV" ]; then
    source .venv/bin/activate
fi
python3 -m twine upload --verbose --repository $PYPI_REPO dist/*
