#!/bin/bash
# SPDX-FileCopyrightText: © 2024 Shaun Wilson
# SPDX-License-Identifier: MIT
set -eo pipefail
if [ -z "$VIRTUAL_ENV" ]; then
    source .venv/bin/activate
fi
if [[ "$1" == "" ]]; then
    pip install sphinx_rtd_theme
fi
cd docs/
make html
