#!/bin/bash
# SPDX-FileCopyrightText: © Shaun Wilson
# SPDX-License-Identifier: MIT
set -eo pipefail
if [ -z "$VIRTUAL_ENV" ]; then
    source .venv/bin/activate
fi
cd docs/
pip install -r requirements.txt
make clean && make html
