#!/usr/bin/env python
# SPDX-FileCopyrightText: © Shaun Wilson
# SPDX-License-Identifier: MIT
##
from subprocess import run
from sys import executable, argv, exit
result = run([ executable, "-m", "punit" ] + argv[1:], check=False)
exit(result.returncode)
