#!/usr/bin/env python
# SPDX-FileCopyrightText: © 2026 Shaun Wilson
# SPDX-License-Identifier: MIT
##
from subprocess import run
from sys import executable, argv
from os import _exit
result = run([executable, "-m", "punit"] + argv[1:], check=False)
_exit(result.returncode)
