#!/bin/bash
# SPDX-FileCopyrightText: © 2024 Shaun Wilson
# SPDX-License-Identifier: MIT
##
set -eo pipefail
if [ -z "$VIRTUAL_ENV" ]; then
    source .venv/bin/activate
fi
PYTHONPATH=src python -m punit --trait '!integration' --trait '!hardcoded' --trait '!longrunning' --trait '!manual' # --report html --output report.html
